### ISSUE TITLE
Submit verification tasks to SV-COMP's NoDataRace category

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#102]
The deadline for submitting verification tasks to SV-COMP 2021 is **9th October**.

I was looking at extracting data-race based test cases from our regression suite and placed them to [my fork of sv-benchmarks](https://github.com/sim642/sv-benchmarks/tree/goblint-regression). I took all non-skip, non-kernel, non-osek regression tests which contain `RACE` or `NORACE` and constructed SV-COMP task definition files (.yml) with the corresponding expected verdict for the new no-data-race property.

Since sv-benchmarks requires everything to compile (preferably without warnings), I had to make some small fixes here and there. Notably I had to replace the use of uninitialized ints for non-determinism (which causes compiler warnings) with `__VERIFIER_nondet_int()`.

## TODO
- [x] Are there any more of the data-race regression benchmarks that should be excluded from submission?
- [x] Are there any more of data-race benchmarks (not just regression) that should be included in the submission? I'm not really sure what https://github.com/goblint/bench has to offer.
- [x] [sv-benchmarks requires all submitted tasks to be accompanied with a license](https://github.com/sosy-lab/sv-benchmarks/blob/master/CONTRIBUTING.md#license). Since the regression tests are from this repo, I suppose [this LICENSE](https://github.com/goblint/analyzer/blob/master/LICENSE) should work. Or is there anything in the regression tests that comes from another source and should be excluded? I'm not familiar with the history of these.

**Comment by sim642** [comment]
While replacing uninitialized local int variables with `__VERIFIER_nondet_int()` is straightforward, there were a couple of uninitialized local pointer variables, where I wasn't so sure. There is also `__VERIFIER_nondet_pointer()` which I currently went with but that may not have been the right thing to do.

### 04-mutex/31-uninitialized
This one does `pthread_mutex_lock` on an uninitialized mutex pointer, which I assume is intentional by the test name.
https://github.com/goblint/analyzer/blob/0610c520ca3fdda91dbc365f44a5e78c76906c6f/tests/regression/04-mutex/31-uninitialized.c#L7-L11
But I'm skeptical about submitting this test because wouldn't the locking of an uninitialized mutex be undefined behavior in the first place? I think SV-COMP doesn't want any undefined behavior.

### 09-regions/05-ptra_rc
This one uses an uninitialized struct pointer `sp` in different ways.
https://github.com/goblint/analyzer/blob/0610c520ca3fdda91dbc365f44a5e78c76906c6f/tests/regression/09-regions/05-ptra_rc.c#L23-L31
I'm not sure what the test is supposed to be doing but it looks awful lot like it should be using `p` (which it just allocates) instead of `sp`.

**Comment by michael-schwarz** [comment]
> 04-mutex/31-uninitialized

Yes, this is UB. So I'd agree to not submit this one to SV-COMP.

> 09-regions/05-ptra_rc

I'd also think it should probably use `p` here. This one is by @kalmera originally, maybe you remember?

>  Are there any more of data-race benchmarks (not just regression) that should be included in the submission? I'm not really sure what https://github.com/goblint/bench has to offer.

Searching for `RACE` here yields no annotations, so it seems like none of these programs have annotations.

**Comment by michael-schwarz** [comment]
Probably one should also go through the examples again, to check that everything annotated as race is actually racy and not just a case in which Goblint doesn't know it will not race.

While doing this, I guess it makes sense to replace `//RACE` with `//RACE!` so we know that is a place in which an actual race can occur.
Searching for `//RACE` and `//RACE!` both yields results, but I don't know how consistently this was done.

**Comment by sim642** [comment]
Regarding the regression test annotation scheme:

I can see the idea behind `RACE` vs `RACE!` but I highly doubt they are used according to these unwritten rules, e.g. there's an instance of `RACE!!11`. Maybe we should be using `FALSE RACE` and `RACE` respectively, if annotated correctly, to make the distinction very clear. Moreover, it doesn't explain `NORACE` vs `NORACE!`.

Similarly there's `NOWARN` vs `NOWARN!` (and an instance of `NOWARN!!1`). I now discovered that there are tests for no data races which entirely use `NOWARN` annotations instead of `NORACE`. The testing suite script at least distinguishes these two but I think it'd be better to use `NORACE` for the lack of races as opposed to the lack of anything to make it clear, what is intended.

**Comment by sim642** [comment]
I'm also thinking if it'd be fine to put `__VERIFIER_nondet_int()` uses in our test suite directly in the places where uninitialized variables are used for nondeterminism. This would make it much easier to have a script for constructing the sv-benchmarks things automatically. As an `extern` function, it'd still give top so nothing should really change for us.

**Comment by michael-schwarz** [comment]
> I can see the idea behind `RACE` vs `RACE!` but I highly doubt they are used according to these unwritten rules, e.g. there's an instance of `RACE!!11`. 

At least in the newer tests, we are using `//UNKNOWN` and `//UNKNOWN!` somewhat consistently, so my suggestion would be to change the annotations to use `//RACE` and `//RACE!` consistently. One could also wonder if it would not be better to remove `//RACE`

> Moreover, it doesn't explain NORACE vs NORACE!.

Yes, there should be no distinction between these two.

> I think it'd be better to use `NORACE` for the lack of races as opposed to the lack of anything to make it clear, what is intended.

I agree.

**Comment by michael-schwarz** [comment]
> I'm also thinking if it'd be fine to put `__VERIFIER_nondet_int()` uses in our test suite directly in the places where uninitialized variables are used for nondeterminism. This would make it much easier to have a script for constructing the sv-benchmarks things automatically. As an `extern` function, it'd still give top so nothing should really change for us.

I don't think there is any reason not to do this, it should however ideally be done consistently everywhere then. Do they ahve support for things such as a non-det structure?

**Comment by sim642** [comment]
> Do they have support for things such as a non-det struct?

They have one such function for nondet void pointer, which I guess could be cast to any struct pointer, unless there's a catch.

**Comment by michael-schwarz** [comment]
> They have one such function for nondet void pointer, which I guess could be cast to any struct pointer, unless there's a catch.

But this doesn't help for a `struct` of storage class `auto` (i.e. stack allocated) such as `struct kala a;` here.

https://github.com/goblint/analyzer/blob/c357940d6e0091a1424a8d117fd1e5d8872a351e/tests/regression/01-cpa/07-structs.c#L20-L26

 So one would have to replace things such as this with an initializer that then sets all the components to sth obtained via these `__VERIFIER_nondet_XXX()`. Same goes for `union`, where we also need to make sure the member that was used last is also unknown.

**Comment by sim642** [comment]
PRs opened to sv-benchmarks:
1. https://github.com/sosy-lab/sv-benchmarks/pull/1164
2. https://github.com/sosy-lab/sv-benchmarks/pull/1168
