### ISSUE TITLE
Remove unmaintained features

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#460]
After Goblint 1.1.0 aka "fat" the plan is to release Goblint 2.0.0 aka "lean", where we have the opportunity to remove numerous unmaintained and deprecated features which might hinder refactoring and development. This issue is to collect ideas for such removals and discuss them.

### Ideas
- [x] **Containment analysis.** Requires LLVM C++ → C conversion, which has been removed upstream. `Goblintutil` has a bunch of name demangling logic specific to that conversion.
- [x] **Deadlocks by races analysis.** Seems suspiciously incomplete: uses must and may locks, but in the predicates completely ignores both. Probably an attempt to implement this paper: https://www.sciencedirect.com/science/article/pii/S2352220814000492.
- [x] **Shapes analysis.** Highly specific to cyclic doubly-linked lists. Builds on region analysis, making the latter more difficult to fix (#107).
- [x] **Non-Apron octagon analysis.**
- [x] **nestra tests.** Currently unused. Should be converted into regression tests (with desired checks added) or just removed.
- [x] **osek**, **osektransactionality**, **flag**, **flagmodes**?
- [x] **`presub` and `postsub`.** They are part of every analysis spec `ctx`, but only used by some old analyses and mostly replaced with queries. During profiling I have noticed that `filter_presubs` can take 10% of runtime manipulating the assoc lists used for `MCP2`. (Might also be a good idea to rewrite that using `Map`?)
    - [x] `postsub` removal is part of #737
    - [x] `presub` is part of #812
- [x] **ListDomain in base analysis.** Very unused, untested and broken. https://github.com/goblint/analyzer/pull/737#discussion_r874431687
- [ ] ~~**condvars analysis.** Unused, not subsumed by var_eq?~~ Now part of #743.
- [x] **Phases.** Currently all phases must be manually specified ahead of time and there's no pure communication between the phases. We probably want something more dynamic _a la_ refinement anyway. The `phases` field in the JSON configuration complicates things due to its recursive schema (#476). #820
- [x] **arinc**? @vogler (#812)
- [x] **extraction** (arinc ~~, osek~~)? #812

**Comment by vesalvojdani** [comment]
So there are some stuff that are more-or-less hopeless, and people will probably not be able to run them in the fat release either... But the OSEK stuff still probably works, but we do not have anyone at the moment to maintain it, so probably we can do this in two steps go for a 1.2.0 "semi-fat" release with all the previous stuff that still runs, and we have enabled regressions tests for. Then, for the 1.2 line, we might want have a monthly action that checks whether it still builds, and we could occasionally back-port stuff to.

**Comment by michael-schwarz** [comment]
I would also like to clean up things such as these strange obfuscated function names:

~~~OCaml
    | `Unknown "F59" (* strcpy *)
    | `Unknown "F60" (* strncpy *)
    | `Unknown "F63" (* memcpy *)
~~~

If we don't want to remove them altogether, they should at least be in some module where one is able to turn them off.

**Comment by sim642** [comment]
Yeah, those appear to be some ARINC obfuscation things that would indeed be nice to get rid of.
The funny thing is, we have a special implementation for those, but not even `memcpy` itself.

**Comment by vogler** [comment]
There's some more ARINC deobfuscation here: https://github.com/goblint/analyzer/blob/87f42a1fb8b473271eb072dd7268d191cbffd56d/src/util/goblintutil.ml#L371-L385

Idk why I didn't use it in `special`. It'd be better to deobfuscate somewhere before such that not every analysis has to take care to do it. Then we could just match `memcpy` etc. there.

**Comment by michael-schwarz** [comment]
I think we should also either remove the tests in the folder [nestra](https://github.com/goblint/analyzer/tree/master/tests/nestra), or add assertions to them and add them to the regression tests.

**Comment by jerhard** [comment]
@vogler We were discussing whether we can remove the Arinc-related analyses and domains, or whether we should keep them for now, in case you need them for some benchmarking or for some other reason.

**Comment by vogler** [comment]
Keep them for now. I'll have a look at them.

**Comment by michael-schwarz** [comment]
Do we want to keep `SolverInteractiveWGlob`? It is some sort of interactive solver that can be started and suspended during solving. Currently, the module is not used anywhere and the solver can thus not be used.

If we want to keep it, we should make it usable and otherwise remove it.
