### ISSUE TITLE
Complete `realloc` support

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#701]
In `LibraryFunctions` we have the following classification for `realloc`:
https://github.com/goblint/analyzer/blob/313793681ce98d1ea2db0e5f853615dd3050095f/src/analyses/libraryFunctions.ml#L62-L66
Surprisingly, for some reason `Realloc` is not handled in base analysis at all, so the default invalidation kicks in, wrecking all we knew about the allocated blob.

### TODO
- [x] Handle `Realloc` in base analysis.
    - [x] Create blob with new size.
    - [x] Copy data from old blob to new blob.
    - [ ] Free old blob.
    - [x] Use mallocWrapper analysis to get a `varinfo` for the new blob.
    - [x] Handle `sem.malloc.fail`.
- [x] Handle `Realloc` in access analysis.
- [x] Handle `Realloc` in region analysis.
