### ISSUE TITLE
Missing library functions for sv-comp

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#868]
Definitions for the following library functions are missing:

**Floats**

- [x] `__builtin_uaddl_overflow` / `__builtin_uadd_overflow` / `__builtin_umull_overflow` Not floats, but still (#869)
- [x] `__isnan`, `__signbit`, `__signbitf`, `_isinff`, `__isinf`, `__isnanf`, `__finite` (#869)
- [x] `fegetround` / `fesetround` (#869)
- [x] `__fpclassify` / `__fpclassifyl` / `__fpclassifyf`  (#869)
- [x] `__builtin_huge_val` /  `__builtin_huge_valf` (#869)
- [x] `__builtin_isgreater` / `__builtin_isgreaterequal` / `__builtin_isless` / `__builtin_islessequal` / `__builtin_islessgreater` / `__builtin_isunordered` (#869)

**Easy to add**

- [x] `pthread_attr_destroy` #878
- [x] `puts` #878
- [x] `strspn` / `strcspn` #878
- [x] `strtoll` / `strtoull` / `strtod` #878
- [x] `mktime` #878
- [x] `clearerr` #878
- [x] `ctime` #878
- [x] `setbuf` #878
- [x] `ntohs` #878
- [x] `__builtin_popcountl` #878
- [x] `swprintf` #878

**Driver / Kernel internals**

- [x] `b1pcmcia_addcard_m2` /  `b1pcmcia_addcard_m1` /  `b1pcmcia_addcard_b1`  (Reported upstream https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/issues/1355)
- [x] `__bad_percpu_size` / `__bad_size_call_parameter` / `__xchg_wrong_size` / `__cmpxchg_wrong_size` / `__xadd_wrong_size` / `__put_user_bad` #878
- [x] `fw_card_release`  (Reported upstream https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/issues/1355)
- [x] `usbnet_read_cmd_nopm` / `usbnet_write_cmd_nopm` / `usbnet_write_cmd` / `usbnet_read_cmd`  (Reported upstream https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/issues/1355)
- [x] `em28xx_free_device`  (Reported upstream https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/issues/1355)
- [x] `smp_send_req`  (Reported upstream https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/issues/1355)
- [x] `rcu_barrier_sched`, `rcu_barrier_bh`, `rcu_barrier`, `synchronize_rcu_expedited`, `synchronize_rcu_bh`  (Reported upstream https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/issues/1355)

**LDV Stubs**

- [x] `ldv_xmalloc` / `ldv_calloc` (Should be fixed in the benchmarks: https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/issues/1349)
- [x] `__VERIFIER_nondet_size_t`, `__VERIFIER_nondet_u16`, `__VERIFIER_nondet_u8`,  `__VERIFIER_nondet_u32`, `__VERIFIER_nondet_loff_t`, `__VERIFIER_nondet_uint128`, `__VERIFIER_nondet_longlong`, `__VERIFIER_nondet_ulonglong`, `__VERIFIER_nondet_unsigned_char`, `__VERIFIER_nondet_const_char_pointer`, `__VERIFIER_nondet_charp` #886 

**Require deeply integrated support**
- [ ] `setjmp` / `longjmp` (tracked in #887)
- [x] `__atomic_store_n` / ` __atomic_load_n` (stop-gap #884)
- [x] `pthread_getspecific` / `pthread_setspecific` (stop-gap #877, tracked as #876)

**Comment by sim642** [comment]
Some of the Linux ones sound like they should be fixed by defining them in the sv-benchmarks themselves.

A couple of the nondet ones are indeed also missing here:
https://github.com/goblint/analyzer/blob/0e49d1ff1727ebfd647eb1227e058d015bcb5785/lib/sv-comp/stub/src/sv-comp.c#L25
I think the issue was that the typedef for `loff_t` only comes in the benchmark itself and might depend on the architecture defined for the benchmark. Although maybe all the Linux tasks have the same architecture, so we can hardcode the specific primitive type.

**Comment by michael-schwarz** [comment]
There is a separate issue for `longjmp` and `setjmp`, so I am closing this issue.
